name: CI-CD

on: push

jobs:
  Model-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup-Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependcies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci-cd.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: DVC Pull
        run: |
          dvc pull

      - name: Test Model Registry
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          pytest tests/test_model_registry.py

      - name: Test Model Performance
        if: success()
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          pytest tests/test_model_performance.py

      - name: Promote Model
        if: success()
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          python scripts/promote_model_to_prod.py

      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | /
          docker login --username AWS / 
          --password-stdin 476114157013.dkr.ecr.eu-north-1.amazonaws.com 

      - name: Build Docker Image
        run: |
          docker build -t inshakhan_ecr .

      - name: Tag Docker Image
        run: |
          docker tag inshakhan_ecr:latest 476114157013.dkr.ecr.eu-north-1.amazonaws.com/inshakhan_ecr:latest          
      
      - name: Push Docker Image to ECR
        run: |
          docker push 476114157013.dkr.ecr.eu-north-1.amazonaws.com/inshakhan_ecr:latest
    